/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DebtorAgent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6340963815739745950L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DebtorAgent\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"BIC\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DebtorAgent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DebtorAgent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DebtorAgent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DebtorAgent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DebtorAgent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DebtorAgent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DebtorAgent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DebtorAgent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DebtorAgent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String BIC;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DebtorAgent() {}

  /**
   * All-args constructor.
   * @param BIC The new value for BIC
   */
  public DebtorAgent(java.lang.String BIC) {
    this.BIC = BIC;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return BIC;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: BIC = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'BIC' field.
   * @return The value of the 'BIC' field.
   */
  public java.lang.String getBIC() {
    return BIC;
  }


  /**
   * Sets the value of the 'BIC' field.
   * @param value the value to set.
   */
  public void setBIC(java.lang.String value) {
    this.BIC = value;
  }

  /**
   * Creates a new DebtorAgent RecordBuilder.
   * @return A new DebtorAgent RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DebtorAgent.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.DebtorAgent.Builder();
  }

  /**
   * Creates a new DebtorAgent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DebtorAgent RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DebtorAgent.Builder newBuilder(com.anz.fastpayment.inward.avro.DebtorAgent.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DebtorAgent.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DebtorAgent.Builder(other);
    }
  }

  /**
   * Creates a new DebtorAgent RecordBuilder by copying an existing DebtorAgent instance.
   * @param other The existing instance to copy.
   * @return A new DebtorAgent RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DebtorAgent.Builder newBuilder(com.anz.fastpayment.inward.avro.DebtorAgent other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DebtorAgent.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DebtorAgent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DebtorAgent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DebtorAgent>
    implements org.apache.avro.data.RecordBuilder<DebtorAgent> {

    private java.lang.String BIC;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DebtorAgent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.BIC)) {
        this.BIC = data().deepCopy(fields()[0].schema(), other.BIC);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing DebtorAgent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DebtorAgent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.BIC)) {
        this.BIC = data().deepCopy(fields()[0].schema(), other.BIC);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'BIC' field.
      * @return The value.
      */
    public java.lang.String getBIC() {
      return BIC;
    }


    /**
      * Sets the value of the 'BIC' field.
      * @param value The value of 'BIC'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DebtorAgent.Builder setBIC(java.lang.String value) {
      validate(fields()[0], value);
      this.BIC = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'BIC' field has been set.
      * @return True if the 'BIC' field has been set, false otherwise.
      */
    public boolean hasBIC() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'BIC' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DebtorAgent.Builder clearBIC() {
      BIC = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DebtorAgent build() {
      try {
        DebtorAgent record = new DebtorAgent();
        record.BIC = fieldSetFlags()[0] ? this.BIC : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DebtorAgent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DebtorAgent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DebtorAgent>
    READER$ = (org.apache.avro.io.DatumReader<DebtorAgent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.BIC == null) {
      throw new IllegalStateException("BIC cannot be null for DebtorAgent encoding");
    }
    out.writeString(this.BIC);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.BIC = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.BIC = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










