/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DirectDebitTransaction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4712672230975868313L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DirectDebitTransaction\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"MndtRltdInf\",\"type\":{\"type\":\"record\",\"name\":\"MandateRelatedInformation\",\"fields\":[{\"name\":\"MndtId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DirectDebitTransaction> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DirectDebitTransaction> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DirectDebitTransaction> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DirectDebitTransaction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DirectDebitTransaction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DirectDebitTransaction to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DirectDebitTransaction from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DirectDebitTransaction instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DirectDebitTransaction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.anz.fastpayment.inward.avro.MandateRelatedInformation MndtRltdInf;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DirectDebitTransaction() {}

  /**
   * All-args constructor.
   * @param MndtRltdInf The new value for MndtRltdInf
   */
  public DirectDebitTransaction(com.anz.fastpayment.inward.avro.MandateRelatedInformation MndtRltdInf) {
    this.MndtRltdInf = MndtRltdInf;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MndtRltdInf;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MndtRltdInf = (com.anz.fastpayment.inward.avro.MandateRelatedInformation)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'MndtRltdInf' field.
   * @return The value of the 'MndtRltdInf' field.
   */
  public com.anz.fastpayment.inward.avro.MandateRelatedInformation getMndtRltdInf() {
    return MndtRltdInf;
  }


  /**
   * Sets the value of the 'MndtRltdInf' field.
   * @param value the value to set.
   */
  public void setMndtRltdInf(com.anz.fastpayment.inward.avro.MandateRelatedInformation value) {
    this.MndtRltdInf = value;
  }

  /**
   * Creates a new DirectDebitTransaction RecordBuilder.
   * @return A new DirectDebitTransaction RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder();
  }

  /**
   * Creates a new DirectDebitTransaction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DirectDebitTransaction RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder newBuilder(com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder(other);
    }
  }

  /**
   * Creates a new DirectDebitTransaction RecordBuilder by copying an existing DirectDebitTransaction instance.
   * @param other The existing instance to copy.
   * @return A new DirectDebitTransaction RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder newBuilder(com.anz.fastpayment.inward.avro.DirectDebitTransaction other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder(other);
    }
  }

  /**
   * RecordBuilder for DirectDebitTransaction instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DirectDebitTransaction>
    implements org.apache.avro.data.RecordBuilder<DirectDebitTransaction> {

    private com.anz.fastpayment.inward.avro.MandateRelatedInformation MndtRltdInf;
    private com.anz.fastpayment.inward.avro.MandateRelatedInformation.Builder MndtRltdInfBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MndtRltdInf)) {
        this.MndtRltdInf = data().deepCopy(fields()[0].schema(), other.MndtRltdInf);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMndtRltdInfBuilder()) {
        this.MndtRltdInfBuilder = com.anz.fastpayment.inward.avro.MandateRelatedInformation.newBuilder(other.getMndtRltdInfBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DirectDebitTransaction instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.DirectDebitTransaction other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.MndtRltdInf)) {
        this.MndtRltdInf = data().deepCopy(fields()[0].schema(), other.MndtRltdInf);
        fieldSetFlags()[0] = true;
      }
      this.MndtRltdInfBuilder = null;
    }

    /**
      * Gets the value of the 'MndtRltdInf' field.
      * @return The value.
      */
    public com.anz.fastpayment.inward.avro.MandateRelatedInformation getMndtRltdInf() {
      return MndtRltdInf;
    }


    /**
      * Sets the value of the 'MndtRltdInf' field.
      * @param value The value of 'MndtRltdInf'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder setMndtRltdInf(com.anz.fastpayment.inward.avro.MandateRelatedInformation value) {
      validate(fields()[0], value);
      this.MndtRltdInfBuilder = null;
      this.MndtRltdInf = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MndtRltdInf' field has been set.
      * @return True if the 'MndtRltdInf' field has been set, false otherwise.
      */
    public boolean hasMndtRltdInf() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'MndtRltdInf' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.anz.fastpayment.inward.avro.MandateRelatedInformation.Builder getMndtRltdInfBuilder() {
      if (MndtRltdInfBuilder == null) {
        if (hasMndtRltdInf()) {
          setMndtRltdInfBuilder(com.anz.fastpayment.inward.avro.MandateRelatedInformation.newBuilder(MndtRltdInf));
        } else {
          setMndtRltdInfBuilder(com.anz.fastpayment.inward.avro.MandateRelatedInformation.newBuilder());
        }
      }
      return MndtRltdInfBuilder;
    }

    /**
     * Sets the Builder instance for the 'MndtRltdInf' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder setMndtRltdInfBuilder(com.anz.fastpayment.inward.avro.MandateRelatedInformation.Builder value) {
      clearMndtRltdInf();
      MndtRltdInfBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'MndtRltdInf' field has an active Builder instance
     * @return True if the 'MndtRltdInf' field has an active Builder instance
     */
    public boolean hasMndtRltdInfBuilder() {
      return MndtRltdInfBuilder != null;
    }

    /**
      * Clears the value of the 'MndtRltdInf' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.DirectDebitTransaction.Builder clearMndtRltdInf() {
      MndtRltdInf = null;
      MndtRltdInfBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DirectDebitTransaction build() {
      try {
        DirectDebitTransaction record = new DirectDebitTransaction();
        if (MndtRltdInfBuilder != null) {
          try {
            record.MndtRltdInf = this.MndtRltdInfBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("MndtRltdInf"));
            throw e;
          }
        } else {
          record.MndtRltdInf = fieldSetFlags()[0] ? this.MndtRltdInf : (com.anz.fastpayment.inward.avro.MandateRelatedInformation) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DirectDebitTransaction>
    WRITER$ = (org.apache.avro.io.DatumWriter<DirectDebitTransaction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DirectDebitTransaction>
    READER$ = (org.apache.avro.io.DatumReader<DirectDebitTransaction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.MndtRltdInf == null) {
      throw new IllegalStateException("MndtRltdInf cannot be null for DirectDebitTransaction encoding");
    }
    this.MndtRltdInf.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.MndtRltdInf == null) {
        this.MndtRltdInf = new com.anz.fastpayment.inward.avro.MandateRelatedInformation();
      }
      this.MndtRltdInf.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.MndtRltdInf == null) {
            this.MndtRltdInf = new com.anz.fastpayment.inward.avro.MandateRelatedInformation();
          }
          this.MndtRltdInf.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










