/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MessageDefinition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5953274390445206839L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageDefinition\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"MsgType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"Schema\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageDefinition> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageDefinition> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MessageDefinition> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MessageDefinition> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MessageDefinition> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MessageDefinition to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MessageDefinition from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MessageDefinition instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MessageDefinition fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String MsgType;
  private java.lang.String Schema;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageDefinition() {}

  /**
   * All-args constructor.
   * @param MsgType The new value for MsgType
   * @param Schema The new value for Schema
   */
  public MessageDefinition(java.lang.String MsgType, java.lang.String Schema) {
    this.MsgType = MsgType;
    this.Schema = Schema;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MsgType;
    case 1: return Schema;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MsgType = value$ != null ? value$.toString() : null; break;
    case 1: Schema = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'MsgType' field.
   * @return The value of the 'MsgType' field.
   */
  public java.lang.String getMsgType() {
    return MsgType;
  }


  /**
   * Sets the value of the 'MsgType' field.
   * @param value the value to set.
   */
  public void setMsgType(java.lang.String value) {
    this.MsgType = value;
  }

  /**
   * Gets the value of the 'Schema' field.
   * @return The value of the 'Schema' field.
   */
  public java.lang.String getSchema$() {
    return Schema;
  }


  /**
   * Sets the value of the 'Schema' field.
   * @param value the value to set.
   */
  public void setSchema$(java.lang.String value) {
    this.Schema = value;
  }

  /**
   * Creates a new MessageDefinition RecordBuilder.
   * @return A new MessageDefinition RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MessageDefinition.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.MessageDefinition.Builder();
  }

  /**
   * Creates a new MessageDefinition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageDefinition RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MessageDefinition.Builder newBuilder(com.anz.fastpayment.inward.avro.MessageDefinition.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MessageDefinition.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MessageDefinition.Builder(other);
    }
  }

  /**
   * Creates a new MessageDefinition RecordBuilder by copying an existing MessageDefinition instance.
   * @param other The existing instance to copy.
   * @return A new MessageDefinition RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.MessageDefinition.Builder newBuilder(com.anz.fastpayment.inward.avro.MessageDefinition other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.MessageDefinition.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.MessageDefinition.Builder(other);
    }
  }

  /**
   * RecordBuilder for MessageDefinition instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageDefinition>
    implements org.apache.avro.data.RecordBuilder<MessageDefinition> {

    private java.lang.String MsgType;
    private java.lang.String Schema;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MessageDefinition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MsgType)) {
        this.MsgType = data().deepCopy(fields()[0].schema(), other.MsgType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Schema)) {
        this.Schema = data().deepCopy(fields()[1].schema(), other.Schema);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MessageDefinition instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.MessageDefinition other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.MsgType)) {
        this.MsgType = data().deepCopy(fields()[0].schema(), other.MsgType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Schema)) {
        this.Schema = data().deepCopy(fields()[1].schema(), other.Schema);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'MsgType' field.
      * @return The value.
      */
    public java.lang.String getMsgType() {
      return MsgType;
    }


    /**
      * Sets the value of the 'MsgType' field.
      * @param value The value of 'MsgType'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MessageDefinition.Builder setMsgType(java.lang.String value) {
      validate(fields()[0], value);
      this.MsgType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MsgType' field has been set.
      * @return True if the 'MsgType' field has been set, false otherwise.
      */
    public boolean hasMsgType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'MsgType' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MessageDefinition.Builder clearMsgType() {
      MsgType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Schema' field.
      * @return The value.
      */
    public java.lang.String getSchema$() {
      return Schema;
    }


    /**
      * Sets the value of the 'Schema' field.
      * @param value The value of 'Schema'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MessageDefinition.Builder setSchema$(java.lang.String value) {
      validate(fields()[1], value);
      this.Schema = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Schema' field has been set.
      * @return True if the 'Schema' field has been set, false otherwise.
      */
    public boolean hasSchema$() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Schema' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.MessageDefinition.Builder clearSchema$() {
      Schema = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageDefinition build() {
      try {
        MessageDefinition record = new MessageDefinition();
        record.MsgType = fieldSetFlags()[0] ? this.MsgType : (java.lang.String) defaultValue(fields()[0]);
        record.Schema = fieldSetFlags()[1] ? this.Schema : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageDefinition>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageDefinition>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageDefinition>
    READER$ = (org.apache.avro.io.DatumReader<MessageDefinition>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.MsgType == null) {
      throw new IllegalStateException("MsgType cannot be null for MessageDefinition encoding");
    }
    out.writeString(this.MsgType);

    if (this.Schema == null) {
      throw new IllegalStateException("Schema cannot be null for MessageDefinition encoding");
    }
    out.writeString(this.Schema);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.MsgType = in.readString();

      this.Schema = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.MsgType = in.readString();
          break;

        case 1:
          this.Schema = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










