/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anz.fastpayment.inward.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ToAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7960271011667561768L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ToAccount\",\"namespace\":\"com.anz.fastpayment.inward.avro\",\"fields\":[{\"name\":\"AcctId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Account identifier\",\"default\":null},{\"name\":\"CurCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Currency code\"},{\"name\":\"Amount\",\"type\":\"double\",\"doc\":\"Transaction amount (legacy field - use AmountMinor for precision)\"},{\"name\":\"AmountMinor\",\"type\":\"long\",\"doc\":\"Transaction amount in minor units (e.g., cents for USD) for precise monetary representation\",\"default\":0},{\"name\":\"Narrative\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"AcctUse\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ToAccount> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ToAccount> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ToAccount> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ToAccount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ToAccount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ToAccount to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ToAccount from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ToAccount instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ToAccount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Account identifier */
  private java.lang.String AcctId;
  /** Currency code */
  private java.lang.String CurCode;
  /** Transaction amount (legacy field - use AmountMinor for precision) */
  private double Amount;
  /** Transaction amount in minor units (e.g., cents for USD) for precise monetary representation */
  private long AmountMinor;
  private java.lang.String Narrative;
  private java.lang.String AcctUse;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ToAccount() {}

  /**
   * All-args constructor.
   * @param AcctId Account identifier
   * @param CurCode Currency code
   * @param Amount Transaction amount (legacy field - use AmountMinor for precision)
   * @param AmountMinor Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
   * @param Narrative The new value for Narrative
   * @param AcctUse The new value for AcctUse
   */
  public ToAccount(java.lang.String AcctId, java.lang.String CurCode, java.lang.Double Amount, java.lang.Long AmountMinor, java.lang.String Narrative, java.lang.String AcctUse) {
    this.AcctId = AcctId;
    this.CurCode = CurCode;
    this.Amount = Amount;
    this.AmountMinor = AmountMinor;
    this.Narrative = Narrative;
    this.AcctUse = AcctUse;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AcctId;
    case 1: return CurCode;
    case 2: return Amount;
    case 3: return AmountMinor;
    case 4: return Narrative;
    case 5: return AcctUse;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AcctId = value$ != null ? value$.toString() : null; break;
    case 1: CurCode = value$ != null ? value$.toString() : null; break;
    case 2: Amount = (java.lang.Double)value$; break;
    case 3: AmountMinor = (java.lang.Long)value$; break;
    case 4: Narrative = value$ != null ? value$.toString() : null; break;
    case 5: AcctUse = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'AcctId' field.
   * @return Account identifier
   */
  public java.lang.String getAcctId() {
    return AcctId;
  }


  /**
   * Sets the value of the 'AcctId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAcctId(java.lang.String value) {
    this.AcctId = value;
  }

  /**
   * Gets the value of the 'CurCode' field.
   * @return Currency code
   */
  public java.lang.String getCurCode() {
    return CurCode;
  }


  /**
   * Sets the value of the 'CurCode' field.
   * Currency code
   * @param value the value to set.
   */
  public void setCurCode(java.lang.String value) {
    this.CurCode = value;
  }

  /**
   * Gets the value of the 'Amount' field.
   * @return Transaction amount (legacy field - use AmountMinor for precision)
   */
  public double getAmount() {
    return Amount;
  }


  /**
   * Sets the value of the 'Amount' field.
   * Transaction amount (legacy field - use AmountMinor for precision)
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.Amount = value;
  }

  /**
   * Gets the value of the 'AmountMinor' field.
   * @return Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
   */
  public long getAmountMinor() {
    return AmountMinor;
  }


  /**
   * Sets the value of the 'AmountMinor' field.
   * Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
   * @param value the value to set.
   */
  public void setAmountMinor(long value) {
    this.AmountMinor = value;
  }

  /**
   * Gets the value of the 'Narrative' field.
   * @return The value of the 'Narrative' field.
   */
  public java.lang.String getNarrative() {
    return Narrative;
  }


  /**
   * Sets the value of the 'Narrative' field.
   * @param value the value to set.
   */
  public void setNarrative(java.lang.String value) {
    this.Narrative = value;
  }

  /**
   * Gets the value of the 'AcctUse' field.
   * @return The value of the 'AcctUse' field.
   */
  public java.lang.String getAcctUse() {
    return AcctUse;
  }


  /**
   * Sets the value of the 'AcctUse' field.
   * @param value the value to set.
   */
  public void setAcctUse(java.lang.String value) {
    this.AcctUse = value;
  }

  /**
   * Creates a new ToAccount RecordBuilder.
   * @return A new ToAccount RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAccount.Builder newBuilder() {
    return new com.anz.fastpayment.inward.avro.ToAccount.Builder();
  }

  /**
   * Creates a new ToAccount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ToAccount RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAccount.Builder newBuilder(com.anz.fastpayment.inward.avro.ToAccount.Builder other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ToAccount.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ToAccount.Builder(other);
    }
  }

  /**
   * Creates a new ToAccount RecordBuilder by copying an existing ToAccount instance.
   * @param other The existing instance to copy.
   * @return A new ToAccount RecordBuilder
   */
  public static com.anz.fastpayment.inward.avro.ToAccount.Builder newBuilder(com.anz.fastpayment.inward.avro.ToAccount other) {
    if (other == null) {
      return new com.anz.fastpayment.inward.avro.ToAccount.Builder();
    } else {
      return new com.anz.fastpayment.inward.avro.ToAccount.Builder(other);
    }
  }

  /**
   * RecordBuilder for ToAccount instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ToAccount>
    implements org.apache.avro.data.RecordBuilder<ToAccount> {

    /** Account identifier */
    private java.lang.String AcctId;
    /** Currency code */
    private java.lang.String CurCode;
    /** Transaction amount (legacy field - use AmountMinor for precision) */
    private double Amount;
    /** Transaction amount in minor units (e.g., cents for USD) for precise monetary representation */
    private long AmountMinor;
    private java.lang.String Narrative;
    private java.lang.String AcctUse;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ToAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.CurCode)) {
        this.CurCode = data().deepCopy(fields()[1].schema(), other.CurCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Amount)) {
        this.Amount = data().deepCopy(fields()[2].schema(), other.Amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.AmountMinor)) {
        this.AmountMinor = data().deepCopy(fields()[3].schema(), other.AmountMinor);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.Narrative)) {
        this.Narrative = data().deepCopy(fields()[4].schema(), other.Narrative);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.AcctUse)) {
        this.AcctUse = data().deepCopy(fields()[5].schema(), other.AcctUse);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ToAccount instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anz.fastpayment.inward.avro.ToAccount other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.AcctId)) {
        this.AcctId = data().deepCopy(fields()[0].schema(), other.AcctId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CurCode)) {
        this.CurCode = data().deepCopy(fields()[1].schema(), other.CurCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Amount)) {
        this.Amount = data().deepCopy(fields()[2].schema(), other.Amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.AmountMinor)) {
        this.AmountMinor = data().deepCopy(fields()[3].schema(), other.AmountMinor);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Narrative)) {
        this.Narrative = data().deepCopy(fields()[4].schema(), other.Narrative);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.AcctUse)) {
        this.AcctUse = data().deepCopy(fields()[5].schema(), other.AcctUse);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'AcctId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.String getAcctId() {
      return AcctId;
    }


    /**
      * Sets the value of the 'AcctId' field.
      * Account identifier
      * @param value The value of 'AcctId'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setAcctId(java.lang.String value) {
      validate(fields()[0], value);
      this.AcctId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AcctId' field has been set.
      * Account identifier
      * @return True if the 'AcctId' field has been set, false otherwise.
      */
    public boolean hasAcctId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AcctId' field.
      * Account identifier
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearAcctId() {
      AcctId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CurCode' field.
      * Currency code
      * @return The value.
      */
    public java.lang.String getCurCode() {
      return CurCode;
    }


    /**
      * Sets the value of the 'CurCode' field.
      * Currency code
      * @param value The value of 'CurCode'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setCurCode(java.lang.String value) {
      validate(fields()[1], value);
      this.CurCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CurCode' field has been set.
      * Currency code
      * @return True if the 'CurCode' field has been set, false otherwise.
      */
    public boolean hasCurCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CurCode' field.
      * Currency code
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearCurCode() {
      CurCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Amount' field.
      * Transaction amount (legacy field - use AmountMinor for precision)
      * @return The value.
      */
    public double getAmount() {
      return Amount;
    }


    /**
      * Sets the value of the 'Amount' field.
      * Transaction amount (legacy field - use AmountMinor for precision)
      * @param value The value of 'Amount'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setAmount(double value) {
      validate(fields()[2], value);
      this.Amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Amount' field has been set.
      * Transaction amount (legacy field - use AmountMinor for precision)
      * @return True if the 'Amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Amount' field.
      * Transaction amount (legacy field - use AmountMinor for precision)
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'AmountMinor' field.
      * Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
      * @return The value.
      */
    public long getAmountMinor() {
      return AmountMinor;
    }


    /**
      * Sets the value of the 'AmountMinor' field.
      * Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
      * @param value The value of 'AmountMinor'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setAmountMinor(long value) {
      validate(fields()[3], value);
      this.AmountMinor = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'AmountMinor' field has been set.
      * Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
      * @return True if the 'AmountMinor' field has been set, false otherwise.
      */
    public boolean hasAmountMinor() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'AmountMinor' field.
      * Transaction amount in minor units (e.g., cents for USD) for precise monetary representation
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearAmountMinor() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'Narrative' field.
      * @return The value.
      */
    public java.lang.String getNarrative() {
      return Narrative;
    }


    /**
      * Sets the value of the 'Narrative' field.
      * @param value The value of 'Narrative'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setNarrative(java.lang.String value) {
      validate(fields()[4], value);
      this.Narrative = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'Narrative' field has been set.
      * @return True if the 'Narrative' field has been set, false otherwise.
      */
    public boolean hasNarrative() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'Narrative' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearNarrative() {
      Narrative = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'AcctUse' field.
      * @return The value.
      */
    public java.lang.String getAcctUse() {
      return AcctUse;
    }


    /**
      * Sets the value of the 'AcctUse' field.
      * @param value The value of 'AcctUse'.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder setAcctUse(java.lang.String value) {
      validate(fields()[5], value);
      this.AcctUse = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'AcctUse' field has been set.
      * @return True if the 'AcctUse' field has been set, false otherwise.
      */
    public boolean hasAcctUse() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'AcctUse' field.
      * @return This builder.
      */
    public com.anz.fastpayment.inward.avro.ToAccount.Builder clearAcctUse() {
      AcctUse = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ToAccount build() {
      try {
        ToAccount record = new ToAccount();
        record.AcctId = fieldSetFlags()[0] ? this.AcctId : (java.lang.String) defaultValue(fields()[0]);
        record.CurCode = fieldSetFlags()[1] ? this.CurCode : (java.lang.String) defaultValue(fields()[1]);
        record.Amount = fieldSetFlags()[2] ? this.Amount : (java.lang.Double) defaultValue(fields()[2]);
        record.AmountMinor = fieldSetFlags()[3] ? this.AmountMinor : (java.lang.Long) defaultValue(fields()[3]);
        record.Narrative = fieldSetFlags()[4] ? this.Narrative : (java.lang.String) defaultValue(fields()[4]);
        record.AcctUse = fieldSetFlags()[5] ? this.AcctUse : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ToAccount>
    WRITER$ = (org.apache.avro.io.DatumWriter<ToAccount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ToAccount>
    READER$ = (org.apache.avro.io.DatumReader<ToAccount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.AcctId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.AcctId);
    }

    if (this.CurCode == null) {
      throw new IllegalStateException("CurCode cannot be null for ToAccount encoding");
    }
    out.writeString(this.CurCode);

    out.writeDouble(this.Amount);

    out.writeLong(this.AmountMinor);

    if (this.Narrative == null) {
      throw new IllegalStateException("Narrative cannot be null for ToAccount encoding");
    }
    out.writeString(this.Narrative);

    if (this.AcctUse == null) {
      throw new IllegalStateException("AcctUse cannot be null for ToAccount encoding");
    }
    out.writeString(this.AcctUse);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.AcctId = null;
      } else {
        this.AcctId = in.readString();
      }

      this.CurCode = in.readString();

      this.Amount = in.readDouble();

      this.AmountMinor = in.readLong();

      this.Narrative = in.readString();

      this.AcctUse = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AcctId = null;
          } else {
            this.AcctId = in.readString();
          }
          break;

        case 1:
          this.CurCode = in.readString();
          break;

        case 2:
          this.Amount = in.readDouble();
          break;

        case 3:
          this.AmountMinor = in.readLong();
          break;

        case 4:
          this.Narrative = in.readString();
          break;

        case 5:
          this.AcctUse = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










