spring:
  application:
    name: fast-inward-clearing-processor
  profiles:
    active: local
  cloud:
    gcp:
      core:
        enabled: true
        project-id: test-project
      spanner:
        enabled: true
        instance-id: test-instance
        database: test-database
        emulator:
          enabled: true
          host: localhost:9010
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 3
      acks: all
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        specific.avro.reader: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Application Configuration
app:
  name: Fast Inward Clearing Processor
  version: 21.0.0-apeafast-SNAPSHOT
  
  # Kafka Topic Configuration
  kafka:
    topics:
      input: transactions.incoming
      output: transactions.processed
      dlq: transactions.dlq
    consumer:
      max-retries: 3
      retry-delay: 1000
      concurrency: 3
    producer:
      acks: all
      retries: 3
      enable-idempotence: true
    schema-registry:
      url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  
  # Business Rules Configuration
  business-rules:
    max-amount: SGD 1000000
    high-risk-countries: XX,YY,ZZ
  
  # Idempotency Configuration
  idempotency:
    ttl-hours: 24
  
  # Processing Configuration
  processing:
    node-id: inward-processor-01
  
  # SLA Configuration
  sla:
    timeout-seconds: ${SLA_TIMEOUT_SECONDS:4.5}
    warning-threshold-seconds: 3.0
    
  # External service endpoints
  external:
    vam-endpoint: ${VAM_ENDPOINT:http://localhost:8445/vam}
    midanz-endpoint: ${MIDANZ_ENDPOINT:http://localhost:8446/midanz}
    liquidity-service-url: ${LIQUIDITY_SERVICE_URL:http://fast-liquidity-service:8080}
    sender-service-url: ${SENDER_SERVICE_URL:http://fast-sender-service:8080}
    
  # Circuit breaker configuration
  circuit-breaker:
    failure-rate-threshold: 50
    wait-duration-in-open-state: 30s
    sliding-window-size: 10

logging:
  level:
    com.anz.fastpayment: DEBUG
    org.springframework.statemachine: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] - %msg%n"

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gcp:
      spanner:
        instance-id: ${SPANNER_INSTANCE:payment-gateway-local}
        database: ${SPANNER_DATABASE:inward-processor-db}
        emulator:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:anz-fastpayment-sg}
      spanner:
        instance-id: ${SPANNER_INSTANCE:payment-gateway}
        database: ${SPANNER_DATABASE:inward-processor-db}