spring:
  application:
    name: fast-sender-service
  profiles:
    active: local

  # Enable Virtual Threads for Java 21
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Application Configuration
app:
  name: Fast Sender Service
  version: 21.0.0-apeafast-SNAPSHOT

  # Message transmission configuration
  sender:
    delivery-timeout-ms: ${DELIVERY_TIMEOUT_MS:10000}
    max-retry-attempts: ${MAX_RETRY_ATTEMPTS:5}
    retry-backoff-ms: ${RETRY_BACKOFF_MS:1000}

  # External service endpoints
  external:
    g3-host-endpoint: ${G3_HOST_ENDPOINT:https://g3host.anz.com/api}
    cpg-endpoint: ${CPG_ENDPOINT:https://cpg.anz.com/gateway}

logging:
  level:
    com.anz.fastpayment: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] - %msg%n"

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gcp:
      spanner:
        instance-id: ${SPANNER_INSTANCE:payment-gateway-local}
        database: ${SPANNER_DATABASE:sender-db}
        emulator:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:anz-fastpayment-sg}
      spanner:
        instance-id: ${SPANNER_INSTANCE:payment-gateway}
        database: ${SPANNER_DATABASE:sender-db}