apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-inward-clearing-processor
  namespace: fast-payment
  labels:
    app: fast-inward-clearing-processor
    version: 21.0.0-apeafast-SNAPSHOT
    component: clearing-processor
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fast-inward-clearing-processor
  template:
    metadata:
      labels:
        app: fast-inward-clearing-processor
        version: 21.0.0-apeafast-SNAPSHOT
        component: clearing-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: fast-inward-clearing-processor-sa
      containers:
      - name: fast-inward-clearing-processor
        image: gcr.io/anz-fastpayment-sg/fast-inward-clearing-processor:21.0.0-apeafast-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: bootstrap-servers
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: port
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: project-id
        - name: SPANNER_INSTANCE
          valueFrom:
            configMapKeyRef:
              name: spanner-config
              key: instance-id
        - name: SPANNER_DATABASE
          valueFrom:
            configMapKeyRef:
              name: spanner-config
              key: database
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: gcr-secret
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: fast-inward-clearing-processor-service
  namespace: fast-payment
  labels:
    app: fast-inward-clearing-processor
    component: clearing-processor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fast-inward-clearing-processor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: fast-payment
data:
  bootstrap-servers: "kafka-broker:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: fast-payment
data:
  host: "redis-master"
  port: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spanner-config
  namespace: fast-payment
data:
  instance-id: "payment-gateway"
  database: "inward-processor-db"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fast-inward-clearing-processor-sa
  namespace: fast-payment
  labels:
    app: fast-inward-clearing-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fast-inward-clearing-processor-role
  namespace: fast-payment
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fast-inward-clearing-processor-rolebinding
  namespace: fast-payment
subjects:
- kind: ServiceAccount
  name: fast-inward-clearing-processor-sa
  namespace: fast-payment
roleRef:
  kind: Role
  name: fast-inward-clearing-processor-role
  apiGroup: rbac.authorization.k8s.io
